"""add user role

Revision ID: 29a911e8e99a
Revises: 99b0c801c678
Create Date: 2025-06-11 14:21:26.984423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "29a911e8e99a"
down_revision: Union[str, None] = "99b0c801c678"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role", sa.VARCHAR(), server_default="user", nullable=False)
    )
    op.create_unique_constraint(None, "user", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")  # type: ignore
    op.drop_column("user", "role")
    # ### end Alembic commands ###
