"""add updated at field review

Revision ID: 8b169caf352f
Revises: 205c063482f5
Create Date: 2025-06-13 12:23:50.980655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b169caf352f"
down_revision: Union[str, None] = "205c063482f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review", sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "updated_at")
    # ### end Alembic commands ###
