"""add user book relation

Revision ID: a39f2394b134
Revises: 29a911e8e99a
Create Date: 2025-06-11 15:58:03.323013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "a39f2394b134"
down_revision: Union[str, None] = "29a911e8e99a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("user_uid", sqlmodel.sql.sqltypes.GUID(), nullable=True)
    )
    op.create_foreign_key(None, "book", "user", ["user_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "book", type_="foreignkey")  # type: ignore
    op.drop_column("book", "user_uid")
    # ### end Alembic commands ###
